Calendar Events
bombies/comp3161-final-project pull request #2
Opened 2024-04-17 04:55 UTC by Nataliazeus94

Contains the implementation of the Calendar events

2024-04-17 05:16 UTC, Nataliazeus94 commented
Calendar Event implemention

2024-04-17 12:33 UTC, bombies requested changes
See changes and re-implement ASAP.

2024-04-17 12:33 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +            "INSERT INTO CalendarEvent (course_id, date, event_name, event_no) VALUES (%s, %s, %s, %s)",
How are you inserting the event_no into the record? That's an auto-generated primary key. Omit that from insertion and remove it from the payload schema.

2024-04-17 12:33 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +@app.route("/calendar", methods=["POST"])
The course_id should be in the route. Remove it from payload schema.

```suggestion
@app.route("/calendar/<str:course_id>", methods=["POST"])
```

2024-04-17 12:33 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +def create_calendar_event():
```suggestion
def create_calendar_event(course_id: str):
```

2024-04-17 12:33 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +@app.route("/calendar/events/student/<int:student_id>/date/<date:date>", methods=["GET"])
This route is too long and it limits what the endpoint could do. Instead, create a schema to allow a startDate and an endDate. The endpoint will handle the results according to said schema.

```suggestion
@app.route("/calendar/events/student/<int:student_id>", methods=["GET"])
```

2024-04-17 12:33 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +def get_student_calendar_events(student_id, date):
```suggestion
def get_student_calendar_events(student_id):
```

2024-04-17 12:33 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +    db_cursor.execute("SELECT * FROM CalendarEvent WHERE date = %s AND course_id IN (SELECT course_id FROM Enrollment WHERE student_id = %s)", (date, student_id))
The payload schema should allow for both an optional start date and an optional end date. Update query to select all events if there is no start/end date provided. If only one field is provided, filter accordingly and if both are provided, select within the range.

2024-04-17 12:33 UTC, bombies commented on modules/routes/calendar/calendar_event_schema.py
> +    event_no = fields.Int(required=True)
```suggestion
```

2024-04-18 14:25 UTC, bombies requested changes

2024-04-18 14:25 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +            "INSERT INTO CalendarEvent (course_id, date, event_name, event_no) VALUES (%s, %s, %s, %s)",
```suggestion
            "INSERT INTO CalendarEvent (course_id, date, event_name) VALUES (%s, %s, %s)",
```

2024-04-18 14:25 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +def get_course_calendar_events(course_id):
This should be a protected route. I'm almost certain I told you all the endpoints in this route should be protected...

```suggestion
@protected_route()
def get_course_calendar_events(course_id):
```

There should also be checks to see if a student is enrolled in the course or if a lecturer teaches the course.

2024-04-18 14:25 UTC, bombies commented on modules/routes/calendar/calendar_event_route.py
> +def get_student_calendar_events(student_id):
```suggestion
@protected([AccountType.Student, AccountType.Admin])
def get_student_calendar_events(student_id):
```

There should also be checks to see if the student ID from the account ID in the session matches the ID passed to the function if the session is a student account.

2024-05-08 02:02 UTC, bombies approved these changes

2024-05-08 02:02 UTC, merged