Forum
bombies/comp3161-final-project pull request #3
Opened 2024-04-17 05:18 UTC by Nataliazeus94

Forum and thread discussion implementation

2024-04-17 05:28 UTC, Nataliazeus94 commented
Forum Implementation

2024-04-17 12:57 UTC, bombies requested changes
fix up

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +def get_course_forums(course_code):
This method needs additional logic to check if the user may be a student/lecturer without access to the course. If that is the case the user should not be able to get the forum.

Also, rename and update it to account for the additional logic to be added.

```suggestion
def handle_couse_forums(course_code):
    if request.method == "GET":
        # Perform original get logic
    else:
        return create_course_forum(course_code)
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@app.route("/forums/course/<string:course_code>", methods=["GET"])
Where is the route protection??

```suggestion
@app.route("/forums/course/<string:course_code>", methods=["GET", "POST"])
@protected_route()
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@app.route("/forums/course/<string:course_code>", methods=["POST"])
This is poor design in Flask. There's a reason the `methods` parameter is an array. Remove this decorator and call the function in the method above.

```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@protected_route(roles=[AccountType.Admin, AccountType.Lecturer])
```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +    body = ForumSchema().load(request.get_json(force=True))
Add checks to see if the user is a student using the `fetch_session()` method. If they are a student, they should not have access to this route. If they are a lecturer, perform a check to see if they teach this course. If they do not, they should not have access to this route. If all checks pass, proceed with logic.

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@app.route("/threads/forum/<int:forum_id>", methods=["GET"])
Route protection??
```suggestion
@app.route("/threads/forum/<int:forum_id>", methods=["GET"])
@protected_route()
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +    db_cursor = db.cursor()
Add checks as stated in an earlier comment.

> Add checks to see if the user is a student using the `fetch_session()` method. If they are a student, they should not have access to this route. If they are a lecturer, perform a check to see if they teach this course. If they do not, they should not have access to this route. If all checks pass, proceed with logic.

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@app.route("/threads/forum/<int:forum_id>", methods=["POST"])
Again, this is bad design. Take advantage of the methods array.

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@app.route("/replies/thread/<int:thread_id>", methods=["POST"])
```suggestion
@app.route("/thread/<int:thread_id>/reply", methods=["POST"])
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@protected_route(roles=[AccountType.Admin, AccountType.Lecturer, AccountType.Student])
```suggestion
@protected_route()
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +def add_thread_to_forum(forum_id):
Add checks as stated in an earlier comment.

> Add checks to see if the user is a student using the `fetch_session()` method. If they are a student, they should not have access to this route. If they are a lecturer, perform a check to see if they teach this course. If they do not, they should not have access to this route. If all checks pass, proceed with logic.

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +def add_reply_to_thread(thread_id):
Add checks as stated in an earlier comment.

> Add checks to see if the user is a student using the `fetch_session()` method. If they are a student, they should not have access to this route. If they are a lecturer, perform a check to see if they teach this course. If they do not, they should not have access to this route. If all checks pass, proceed with logic.

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_schema.py
> +    creator = fields.Int(required=True)
There is no need for this field. It will be inherited from the session.

```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_schema.py
> +    user_id = fields.Int(required=True)
Again, no need for this field. Will be inherited from session.

```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +    user_id = fetch_session(request.headers.get("Authorization"))
```suggestion
    user_id = fetch_session()["sub"]
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +    user_id = fetch_session(request.headers.get("Authorization"))
```suggestion
    user_id = fetch_session()["sub"]
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +            (body["topic"], body["post_time"], body["creator"], body["course_code"]),
The creator should be inherited from the session.

Also, why are you getting the post time from the body?? That should be handled by the API...

```suggestion
            (body["topic"], date.today(), fetch_session()["sub"], body["course_code"]),
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_schema.py
> +    post_time = fields.DateTime(required=True)
```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_schema.py
> +    reply_time = fields.DateTime(required=True)
```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +            "INSERT INTO DiscussionReply (thread_id, user_id, reply_text) VALUES (%s, %s, %s)",
Why'd you leave off the reply time?
```suggestion
            "INSERT INTO DiscussionReply (thread_id, user_id, reply_text, reply_time) VALUES (%s, %s, %s, %s)",
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +            (thread_id, user_id, body["reply_text"]),
```suggestion
            (thread_id, user_id, body["reply_text"], date.today()),
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_schema.py
> +    reply_id = fields.Int(dump_only=True)
```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_schema.py
> +    thread_id = fields.Int(dump_only=True)
```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_schema.py
> +    forum_id = fields.Int(dump_only=True)
```suggestion
```

2024-04-17 12:57 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +
```suggestion
from datetime import date

```

2024-04-18 14:17 UTC, bombies requested changes

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@protected_route(roles=[AccountType.Admin, AccountType.Lecturer])
```suggestion
@protected_route()
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +    if request.method == "GET":
Logic to check if a student is enrolled for this course or if a lecturer teaches this course should be implemented here.

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +from modules.utils.auth_utils import fetch_session
??????????????????

```suggestion
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +    # Check if the user is a student
This is not necessary. Based on the `protected_route` decorator it only allows for Admins for Lecturers to access the route anyways.

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@app.route("/threads/forum/<int:forum_id>", methods=["POST"])
Why does this still exist??? This isn't supposed to be a route in itself... You updated the methods array but didn't update the logic at all.

```suggestion
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@protected_route(roles=[AccountType.Admin, AccountType.Lecturer, AccountType.Student])
```suggestion
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +@protected_route(roles=[AccountType.Admin, AccountType.Lecturer])
```suggestion
@protected_route()
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +    # Check if the user is a student
```suggestion
    if request.method == "GET":
        # Handle get logic
    else:
        # Handle post logic
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +def handle_forum_threads(forum_id, course_code):
How is `course_code` a parameter??

```suggestion
def handle_forum_threads(forum_id: int):
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +def add_thread_to_forum(forum_id, course_code):
You didn't even use a course code?

```suggestion
def add_thread_to_forum(forum_id: int):
```

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +        return jsonify({"message": "Students are not allowed to create forums"}), 403
They're not creating a forum, they're creating a thread which students should be able to do... The only time a student should not be able to make a thread in a forum is if they are not enrolled for the course the forum is in.

2024-04-18 14:17 UTC, bombies commented on modules/routes/Forums/forum_route.py
> +
Where are the checks to see if a student is enrolled for the course or a lecturer teaches the course??

2024-05-07 00:08 UTC, merged